apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uoezwjcjl-go 
  janus-idp.io/tekton: uoezwjcjl-go
  backstage.io/kubernetes-id: uoezwjcjl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uoezwjcjl-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  